version: "3.8"

services:
  sheet:
    build: .
    restart: always
    ports:
      - 5000:5000
    environment:
      - HOST=http://localhost:5000
      - APP_FOLDER=/pathfinder
      - GOOGLE_CLIENT_ID=<id>.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=<secret>
      - GITHUB_CLIENT_ID=<id>
      - GITHUB_CLIENT_SECRET=<secret>
      - MONGOLAB_PAID=mongodb://sheet:<mongodb_password>@mongo:27017/sheet
    depends_on:
      - mongo

  mongo:
    image: mongo:4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: sheet
      MONGO_INITDB_ROOT_PASSWORD: <mongodb_password>
